-- IN PROGRESS

-- MySQL Script generated by MySQL Workbench
-- Sun 25 Sep 2022 10:57:08 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbOficina` DEFAULT CHARACTER SET UTF8MB4;
drop database `dbOficina`;
USE `dbOficina`;

-- -----------------------------------------------------
-- Table `mydb`.`Natural_Person`
-- -----------------------------------------------------
drop table `Natural_Person`;
CREATE TABLE IF NOT EXISTS `dbOficina`.`NaturalPerson` (
  `idNaturalPerson` INT NOT NULL AUTO_INCREMENT,
  `CPF` CHAR(11) NOT NULL,
  `Fname` VARCHAR(15) NOT NULL,
  `Mname` VARCHAR(15) NOT NULL,
  `Lname` VARCHAR(15) NOT NULL,
  `Bdate` DATE NOT NULL,
  `Address` VARCHAR(300) NOT NULL,
  `NP_Type` ENUM('Client', 'Mechanic') NOT NULL,
  PRIMARY KEY (`idNaturalPerson`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;
desc NaturalPerson;

-- -----------------------------------------------------
-- Table `mydb`.`Mechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`Mechanic` (
  `idMechanic` INT NOT NULL,
  `Expertise` VARCHAR(45) NOT NULL,
  `NaturalPerson_idNaturalPerson` INT NOT NULL,
  PRIMARY KEY (`idMechanic`, `NaturalPerson_idNaturalPerson`),
  INDEX `fk_Mechanic_NaturalPerson1_idx` (`NaturalPerson_idNaturalPerson` ASC) VISIBLE,
  CONSTRAINT `fk_Mechanic_Natural_Person1`
    FOREIGN KEY (`NaturalPerson_idNaturalPerson`)
    REFERENCES `dbOficina`.`NaturalPerson` (`idNaturalPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Legal_Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`LegalPerson` (
  `idLegalPerson` INT NOT NULL AUTO_INCREMENT,
  `CNPJ` CHAR(14) NOT NULL,
  `Corporate_Name` VARCHAR(45) NOT NULL,
  `Trade_Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idLegalPerson`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `Corporate_Name_UNIQUE` (`Corporate_Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`Boleto` (
  `idBoleto` INT NOT NULL AUTO_INCREMENT,
  `Boleto_Value` FLOAT NOT NULL,
  PRIMARY KEY (`idBoleto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cred_Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`Cred_Card` (
  `idCred_Card` INT NOT NULL AUTO_INCREMENT,
  `Card_Number` CHAR(16) NOT NULL,
  `Expiration_Date` DATE NOT NULL,
  `Name_on_Card` VARCHAR(45) NOT NULL,
  `Security_Code` INT(3) NOT NULL,
  `Installments_Plan` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idCred_Card`),
  UNIQUE INDEX `Card_Number_UNIQUE` (`Card_Number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PIX`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`PIX` (
  `idPIX` INT NOT NULL AUTO_INCREMENT,
  `Type_Key` ENUM('CPF', 'CNPJ', 'Phone', 'E-mail', 'Aleatory Key') NOT NULL,
  PRIMARY KEY (`idPIX`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`Payment` (
  `idPayment` INT NOT NULL AUTO_INCREMENT,
  `Payment_Method` ENUM('Boleto', 'PIX', 'Cred Card') NULL DEFAULT 'Cred Card',
  `Boleto_idBoleto` INT NOT NULL,
  `Cred_Card_idCred_Card` INT NOT NULL,
  `PIX_idPIX` INT NOT NULL,
  PRIMARY KEY (`idPayment`, `Boleto_idBoleto`, `Cred_Card_idCred_Card`, `PIX_idPIX`),
  INDEX `fk_Payment_Boleto1_idx` (`Boleto_idBoleto` ASC) VISIBLE,
  INDEX `fk_Payment_Cred_Card1_idx` (`Cred_Card_idCred_Card` ASC) VISIBLE,
  INDEX `fk_Payment_PIX1_idx` (`PIX_idPIX` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Boleto1`
    FOREIGN KEY (`Boleto_idBoleto`)
    REFERENCES `dbOficina`.`Boleto` (`idBoleto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_Cred_Card1`
    FOREIGN KEY (`Cred_Card_idCred_Card`)
    REFERENCES `mydb`.`Cred_Card` (`idCred_Card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_PIX1`
    FOREIGN KEY (`PIX_idPIX`)
    REFERENCES `mydb`.`PIX` (`idPIX`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`Client` (
  `idClient` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Birth_Date` DATE NOT NULL,
  `Client_Id_Doc` ENUM('CPF', 'CNPJ') NOT NULL,
  `Vehicle_Model` VARCHAR(45) NOT NULL,
  `Mechanic_idMechanic` INT NOT NULL,
  `NaturalPerson_idNaturalPerson` INT NOT NULL,
  `LegalPerson_idLegalPerson` INT NOT NULL,
  `Payment_idPayment` INT NOT NULL,
  PRIMARY KEY (`idClient`, `Mechanic_idMechanic`, `NaturalPerson_idNaturalPerson`, `LegalPerson_idLegalPerson`, `Payment_idPayment`),
  INDEX `fk_Client_Mechanic_idx` (`Mechanic_idMechanic` ASC) VISIBLE,
  INDEX `fk_Client_NaturalPerson1_idx` (`NaturalPerson_idNaturalPerson` ASC) VISIBLE,
  INDEX `fk_Client_LegalPerson1_idx` (`LegalPerson_idLegalPerson` ASC) VISIBLE,
  INDEX `fk_Client_Payment1_idx` (`Payment_idPayment` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Mechanic`
    FOREIGN KEY (`Mechanic_idMechanic`)
    REFERENCES `dbOficina`.`Mechanic` (`idMechanic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_NaturalPerson1`
    FOREIGN KEY (`NaturalPerson_idNaturalPerson`)
    REFERENCES `dbOficina`.`NaturalPerson` (`idNaturalPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_LegalPerson1`
    FOREIGN KEY (`LegalPerson_idLegalPerson`)
    REFERENCES `dbOficina`.`LegalPerson` (`idLegalPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Payment1`
    FOREIGN KEY (`Payment_idPayment`)
    REFERENCES `dbOficina`.`Payment` (`idPayment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`Service` (
  `idService` INT NOT NULL,
  `Service_Type` ENUM('Repair', 'Routine maintenance') NOT NULL DEFAULT 'Routine maintenance',
  `Value` FLOAT NOT NULL,
  `Description_Repair_Type` VARCHAR(45) NULL,
  `Mechanic_idMechanic` INT NOT NULL,
  `Status` ENUM('Client approved service', 'Client disapproved service') NOT NULL DEFAULT 'Client approved service',
  PRIMARY KEY (`idService`, `Mechanic_idMechanic`),
  INDEX `fk_Service_Mechanic1_idx` (`Mechanic_idMechanic` ASC) VISIBLE,
  CONSTRAINT `fk_Service_Mechanic1`
    FOREIGN KEY (`Mechanic_idMechanic`)
    REFERENCES `dbOficina`.`Mechanic` (`idMechanic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela de referência de mão-de-obra';


-- -----------------------------------------------------
-- Table `mydb`.`Order_Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`Order_Service` (
  `idOrder_Service` INT NOT NULL AUTO_INCREMENT,
  `Value` FLOAT NOT NULL,
  `Start_date` DATE NOT NULL,
  `Delivery_date` DATE NOT NULL,
  `Status` ENUM('In progress', 'Finished', 'Delivered') NOT NULL DEFAULT 'In progress',
  `Service_idService` INT NOT NULL,
  `Service_Mechanic_idMechanic` INT NOT NULL,
  PRIMARY KEY (`idOrder_Service`, `Service_idService`, `Service_Mechanic_idMechanic`),
  INDEX `fk_Order_Service_Service1_idx` (`Service_idService` ASC, `Service_Mechanic_idMechanic` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Service_Service1`
    FOREIGN KEY (`Service_idService` , `Service_Mechanic_idMechanic`)
    REFERENCES `dbOficina`.`Service` (`idService` , `Mechanic_idMechanic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOficina`.`Car_Parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`Car_Parts` (
  `idCar_Parts` INT NOT NULL AUTO_INCREMENT,
  `Value` FLOAT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCar_Parts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOficina`.`Service_has_Car_Parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbOficina`.`Service_has_Car_Parts` (
  `Service_idService_Value` INT NOT NULL,
  `Car_Parts_idCar_Parts` INT NOT NULL,
  PRIMARY KEY (`Service_idService_Value`, `Car_Parts_idCar_Parts`),
  INDEX `fk_Service_has_Car_Parts_Car_Parts1_idx` (`Car_Parts_idCar_Parts` ASC) VISIBLE,
  INDEX `fk_Service_has_Car_Parts_Service1_idx` (`Service_idService_Value` ASC) VISIBLE,
  CONSTRAINT `fk_Service_has_Car_Parts_Service1`
    FOREIGN KEY (`Service_idService_Value`)
    REFERENCES `dbOficina`.`Service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_has_Car_Parts_Car_Parts1`
    FOREIGN KEY (`Car_Parts_idCar_Parts`)
    REFERENCES `dbOficina`.`Car_Parts` (`idCar_Parts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbOficina`.`Order_Service_has_Mechanic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_Service_has_Mechanic` (
  `Order_Service_idOrder_Service` INT NOT NULL,
  `Mechanic_idMechanic` INT NOT NULL,
  PRIMARY KEY (`Order_Service_idOrder_Service`, `Mechanic_idMechanic`),
  INDEX `fk_Order_Service_has_Mechanic_Mechanic1_idx` (`Mechanic_idMechanic` ASC) VISIBLE,
  INDEX `fk_Order_Service_has_Mechanic_Order_Service1_idx` (`Order_Service_idOrder_Service` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Service_has_Mechanic_Order_Service1`
    FOREIGN KEY (`Order_Service_idOrder_Service`)
    REFERENCES `dbOficina`.`Order_Service` (`idOrder_Service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Service_has_Mechanic_Mechanic1`
    FOREIGN KEY (`Mechanic_idMechanic`)
    REFERENCES `dbOficina`.`Mechanic` (`idMechanic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
